//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by MPlayerGUI.rc
//
#define IDD_ABOUTBOX                    100
#define IDD_PROGRESS_DLGBAR             103
#define IDD_PROPPAGE_FILE               106
#define IDD_PROPPAGE_PATH               107
#define IDR_MAINFRAME                   128
#define IDR_MPLAYETYPE                  129
#define IDR_MYTOOLBAR                   129
#define IDB_BITMAP_MPLAYER_LOGO         130
#define IDB_BITMAP_BLACK                132
#define IDD_CLIP_PROPERTY               134
#define IDD_PREFERENCES                 136
#define IDD_PLAYLIST                    137
#define IDB_BITMAP_VIDEOPANEL           138
#define IDD_VSETTINGS                   139
#define IDD_PROPPAGE_OUTPUT             140
#define IDD_PROPPAGE_PLAYER             141
#define IDR_MENU_CONTEXT                142
#define IDD_PROPPAGE_ADVANCED           142
#define IDD_OPENURL                     148
#define IDD_GOTO                        150
#define IDD_PROPPAGE_SUBTITLES          151
#define IDD_PROPPAGE_VIDEO              152
#define IDD_PROPPAGE_CONTENT            153
#define IDD_PLAYER_STATUSBAR            154
#define IDD_PROPPAGE_ASSOCIATION        155
#define IDI_ENGINE                      159
#define IDI_OUTPUT                      160
#define IDI_SUBTITLE                    161
#define IDI_VIDEO                       162
#define IDI_ADVANCED                    163
#define IDI_NETRADIO                    164
#define IDI_NET_OUT                     165
#define IDI_AUDIO_NO_AUDIO              166
#define IDI_AUDIO_STEREOL               167
#define IDI_AUDIO_STEREOR               168
#define IDI_FILE_BLANK                  169
#define IDI_FILE_LOCALMEDIA             170
#define IDI_NET_BUFFERING               171
#define IDI_NET_INOUT                   172
#define IDI_NET_OK                      173
#define IDI_AUDIO_MONO                  174
#define IDI_NET_REC_020                 175
#define IDI_ALERT                       177
#define IDD_LOG                         179
#define IDI_SHUTDOWN                    180
#define IDD_SHUTDOWN                    181
#define IDI_KEYBOARD                    182
#define IDD_PROPPAGE_COMMANDS           182
#define IDD_SENDCOMMAND                 183
#define IDC_SLIDER_PROGRESS             1000
#define IDC_SLIDER_VOLUME               1001
#define IDC_CHECK_SHOW_TOOLBAR          1002
#define IDC_CHECK_SHOW_STATUSBAR        1003
#define IDC_CHECK_SHOW_PROGRESSBAR      1004
#define IDC_EDIT_CLIP                   1005
#define IDC_CHECK_SHOW_PLAYLIST         1005
#define IDC_EDIT_TITLE                  1005
#define IDC_EDIT_AUTHOR                 1006
#define IDC_EDIT_ARTIST                 1006
#define IDC_EDIT_COPYRIGHT              1007
#define IDC_EDIT_ALBUM                  1007
#define IDC_EDIT_RATING                 1008
#define IDC_EDIT_GENRE                  1008
#define IDC_EDIT_ACODEC                 1009
#define IDC_EDIT_AFORMAT                1010
#define IDC_COMBO_SSDISABLEMODE         1010
#define IDC_EDIT_ABITRATE               1011
#define IDC_EDIT_MPLAYER_USER_CONFIG    1011
#define IDC_EDIT_ARATE                  1012
#define IDC_LIST_PLAYLIST               1012
#define IDC_COMBO_VIDEOOUTPUTDRIVER     1012
#define IDC_BUTTON_PL_STARTPLAY         1013
#define IDC_COMBO_AUDIOOUTPUTDRIVER     1013
#define IDC_EDIT_NCH                    1013
#define IDC_BUTTON_PL_ADD               1014
#define IDC_BUTTON_PL_MOVEUP            1015
#define IDC_EDIT_MPLAYER_PATH           1016
#define IDC_BUTTON_PL_MOVEDOWN          1016
#define IDC_EDIT_MPLAYER_PATHNAME       1016
#define IDC_BUTTON_PL_REMOVE            1017
#define IDC_BUTTON_PL_REMOVEALL         1018
#define IDC_EDIT_VCODEC                 1019
#define IDC_BUTTON_VS_RESET             1019
#define IDC_BUTTON_PL_LOAD              1019
#define IDC_EDIT_VBITRATE               1020
#define IDC_BUTTON_PATHBROWSE           1020
#define IDC_SLIDER_BRIGHTNESS           1020
#define IDC_BUTTON_PL_SHUFFLE           1020
#define IDC_BUTTON_PATHNAMEBROWSE       1020
#define IDC_EDIT_VWIDTH                 1021
#define IDC_RADIO_USEDEFAULTPATH        1021
#define IDC_SLIDER_CONTRAST             1021
#define IDC_EDIT_VHEIGHT                1022
#define IDC_RADIO_USESPECIFIEDPATH      1022
#define IDC_SLIDER_HUE                  1022
#define IDC_EDIT_VFPS                   1023
#define IDC_SLIDER_SATURATION           1023
#define IDC_CHECK_SHOW_VIDEOSETTINGS    1023
#define IDC_EDIT_LENGTH                 1024
#define IDC_OPENURL                     1026
#define IDC_EDIT_GOTO_H                 1027
#define IDC_EDIT_GOTO_M                 1028
#define IDC_EDIT_GOTO_S                 1029
#define IDC_CHECK_DOUBLEBUFFERING       1030
#define IDC_CHECK_AUTOLOADSUB           1032
#define IDC_CHECK_ALLOWMULTIPLEINSTANCES 1033
#define IDC_BUTTON_PL_SAVE              1034
#define IDC_CHECK_AUTOSHUFFLE           1034
#define IDC_SPIN_H                      1035
#define IDC_CHECK_STARTUP_AOT           1035
#define IDC_SPIN_M                      1036
#define IDC_SPIN_S                      1037
#define IDC_COMBO_MPLAYER_PRIORITY      1037
#define IDC_CHECK_ENABLEMPLAYERMONITOR  1038
#define IDC_BUTTON_PL_SORT              1039
#define IDC_BUTTON_VIDEO_RESET          1044
#define IDC_EDIT_BRIGHTNESS             1045
#define IDC_EDIT_CONTRAST               1046
#define IDC_EDIT_FILE_LENGTH            1046
#define IDC_EDIT_HUE                    1047
#define IDC_EDIT_FILE_BITRATE           1047
#define IDC_EDIT_SATURATION             1048
#define IDC_EDIT_FILE_MEDIATYPE         1048
#define IDC_EDIT_FILE_VIDEOSIZE         1049
#define IDC_EDIT_FILE_ASPECTRATIO       1050
#define IDC_EDIT_FILE_AUDIOCODEC        1051
#define IDC_EDIT_FILE_VIDEOCODEC        1052
#define IDC_EDIT_FILE_LOCATION          1053
#define IDC_EDIT_CONTENT_TITLE          1054
#define IDC_EDIT_CONTENT_ARTIST         1055
#define IDC_EDIT_FONTPATHNAME           1055
#define IDC_EDIT_CONTENT_COPYRIGHT      1056
#define IDC_BUTTON_PICKFONT             1056
#define IDC_EDIT_CONTENT_GENRE          1057
#define IDC_COMBO_SUBCP                 1057
#define IDC_EDIT_CONTENT_COMMENTS       1058
#define IDC_CHECK_LAUNCHINFULLSCREEN    1058
#define IDC_EDIT_CONTENT_COMPOSER       1059
#define IDC_EDIT_EXTENSIONS             1059
#define IDC_CHECK_REMEMBERLASTPLAYBACKPOSITION 1059
#define IDC_EDIT_CONTENT_ALBUM          1060
#define IDC_BUTTON_EXT_LOAD             1060
#define IDC_CHECK_SHOWCONTROLSINFULLSCREEN 1060
#define IDC_EDIT_CONTENT_RATING         1062
#define IDC_BUTTON_EXT_ASSOCIATE        1062
#define IDC_EDIT_LOG                    1064
#define IDC_BUTTON_LOG_RESET            1065
#define IDC_CHECK_ENABLELOGGING         1066
#define IDC_EDIT_SHUTDOWN_COUNTER       1067
#define IDC_EDIT_PRESETZOOM             1068
#define IDC_EDIT_F1CMD                  1070
#define IDC_EDIT_F2CMD                  1071
#define IDC_EDIT_F3CMD                  1072
#define IDC_EDIT_MPLAYERMONITOR_THRESHOLD 1072
#define IDC_EDIT_F4CMD                  1073
#define IDC_EDIT_SENDCOMMAND            1073
#define IDC_EDIT_F5CMD                  1074
#define IDC_CHECK_ENABLEARGUMENTVOLUME  1074
#define IDC_EDIT_F6CMD                  1075
#define IDC_CHECK_ALLOWSENDCMDWHILEPAUSED 1075
#define IDC_EDIT_F7CMD                  1076
#define IDC_EDIT_F8CMD                  1077
#define ID_PLAY_PLAY                    32771
#define ID_PLAY_STOP                    32772
#define ID_PLAY_PAUSE                   32773
#define ID_FILE_CLOSE_FILE              32774
#define ID_VIEW_FULLSCREEN              32785
#define ID_FILE_CLIPPROPERTY            32786
#define ID_VIEW_ALWAYSONTOP             32787
#define ID_VIEW_KEEPASPECTRATIO         32788
#define ID_VIEW_PROGRESS_BAR            32789
#define ID_PLAY_FF10S                   32790
#define ID_PLAY_REW10S                  32791
#define ID_PLAY_FF1M                    32792
#define ID_PLAY_REW1M                   32793
#define ID_PLAY_FF10M                   32794
#define ID_PLAY_REW10M                  32795
#define ID_PLAY_REPEAT                  32796
#define ID_VOLUME_100                   32797
#define ID_VOLUME_75                    32798
#define ID_VOLUME_50                    32799
#define ID_VOLUME_25                    32800
#define ID_VOLUME_MUTE                  32801
#define ID_OPTIONS_PREFERENCES          32802
#define ID_VIEW_PLAYLIST                32803
#define ID_VIEW_VIDEOSETTINGS           32813
#define ID_DUMMY                        32814
#define ID_VIEW_MYTOOLBAR               32818
#define ID_OPTIONS_SAVESETTINGS         32819
#define ID_PLAY_NEXT                    32822
#define ID_PLAY_PREVIOUS                32823
#define ID_FILE_OPENURL                 32824
#define ID_PLAY_GOTO                    32825
#define ID_VIEW_STATUSBAR               32827
#define ID_HELP_HOMEPAGE                32828
#define ID_VIEW_LOG                     32829
#define ID_PLAY_AFTERPLAYBACK_SHUTDOWN  32833
#define ID_PLAY_AFTERPLAYBACK_DONOTHING 32834
#define ID_VIEW_ZOOMHALF                32836
#define ID_VIEW_ZOOM1X                  32837
#define ID_VIEW_ZOOM2X                  32838
#define ID_VIEW_ZOOMPRESET              32839
#define ID_PLAY_SENDCOMMAND             32840
#define ID_F1CMD                        35001
#define ID_F2CMD                        35002
#define ID_F3CMD                        35003
#define ID_F4CMD                        35004
#define ID_F5CMD                        35005
#define ID_F6CMD                        35006
#define ID_F7CMD                        35007
#define ID_F8CMD                        35008
#define ID_INDICATOR_TIME               59144
#define ID_INDICATOR_LENGTH             59145
#define ID_INDICATOR_STATUS             59146
#define ID_INDICATOR_ABPS               59147
#define IDS_MPLAYER_PLAYING_SINGLE      61204
#define IDS_MPLAYER_PAUSE               61205
#define IDS_MPLAYER_STOP                61206
#define IDS_MPLAYER_ASKTOSTART          61207
#define IDS_MPLAYER_FAILED              61208
#define IDS_MPLAYER_PLAYING_LIST        61209
#define IDS_MPLAYER_ASKTOQUIT           61210
#define IDS_MPLAYER_FILENOTEXIST        61211
#define IDS_MPLAYER_NOENGINE            61212

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        184
#define _APS_NEXT_COMMAND_VALUE         32841
#define _APS_NEXT_CONTROL_VALUE         1075
#define _APS_NEXT_SYMED_VALUE           112
#endif
#endif
